// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGuZZbNtXM8WBqQ8435_HfnhXBtG5Dh_4',
    appId: '1:964177904515:web:108c2aebfb70b4d0c1ecb6',
    messagingSenderId: '964177904515',
    projectId: 'go90stores-6583a',
    authDomain: 'go90stores-6583a.firebaseapp.com',
    storageBucket: 'go90stores-6583a.firebasestorage.app',
    measurementId: 'G-9SX1ZQ4VYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAssIoHUTK9LqkuB_judYtzsVvsJDwPIQ4',
    appId: '1:964177904515:android:41f184147f38a7ddc1ecb6',
    messagingSenderId: '964177904515',
    projectId: 'go90stores-6583a',
    storageBucket: 'go90stores-6583a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQh_THJXLVfLWcHi9QmutgEvGsdSs4O8',
    appId: '1:964177904515:ios:6755699f457af8a0c1ecb6',
    messagingSenderId: '964177904515',
    projectId: 'go90stores-6583a',
    storageBucket: 'go90stores-6583a.firebasestorage.app',
    iosBundleId: 'com.go90stores.in',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqQh_THJXLVfLWcHi9QmutgEvGsdSs4O8',
    appId: '1:964177904515:ios:38a504541858aa92c1ecb6',
    messagingSenderId: '964177904515',
    projectId: 'go90stores-6583a',
    storageBucket: 'go90stores-6583a.firebasestorage.app',
    iosBundleId: 'com.example.go90stores',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGuZZbNtXM8WBqQ8435_HfnhXBtG5Dh_4',
    appId: '1:964177904515:web:4b27ffcd671155bbc1ecb6',
    messagingSenderId: '964177904515',
    projectId: 'go90stores-6583a',
    authDomain: 'go90stores-6583a.firebaseapp.com',
    storageBucket: 'go90stores-6583a.firebasestorage.app',
    measurementId: 'G-TLY37PKXS6',
  );

}